### ISSUE TITLE
Tickets Tags are not being retrieved

### ISSUE THREAD

**Issue by dylan-stitch** [singer-io/tap-freshdesk#22]
The `tags` attribute is included in the schema for the `tickets` table, but this attribute does not appear to be replicated despite tickets which have tags in the source account having been replicated already.

This is occurring in the Stitch production environment using version 0.9.0.

**Comment by perplexes** [comment]
In the ["list all tickets" endpoint](https://developers.freshdesk.com/api/#list_all_tickets), it doesn't return the tags as part of the tickets there (see also [this thread](https://support.freshdesk.com/support/discussions/topics/305604/page/1?url_locale=)), you have to call the API for *each* ticket to get the API to return tags.

We're running into this because as part of development work we want to see that number of a particular kind of ticket go down.

**Comment by KAllan357** [comment]
I apologize for not merging this but it looks like in August Freshdesk added support for this on just the List endpoint: https://support.freshdesk.com/support/discussions/topics/322113
